# NUMPY ARRAY LIBRARY


In [10]:
# import numpy library
import numpy as np

#  [  ]    single dimention

In [12]:
list = [1,2,3,4]           
np.array(list)             
array_ = np.array(list)

# ([ [ ] ])   two dimension

In [17]:
list1 = [2,4,5,6,7]
list2 = [9,8,6,7,5]
list3 = [8,6,7,5,4]
arr1 = np.array([list1,list2,list3])
print(arr1)
arr1.shape       #numbers of rows and column it is a property (3,5) where 3 is a row and 5 is a column
#horizontal - row
#vertical - column


[[2 4 5 6 7]
 [9 8 6 7 5]
 [8 6 7 5 4]]


(3, 5)

In [13]:
print(type(array_))            # type of numpy array

<class 'numpy.ndarray'>


# Indexing

In [18]:
arr1

array([[2, 4, 5, 6, 7],
       [9, 8, 6, 7, 5],
       [8, 6, 7, 5, 4]])

In [23]:
arr1[:,1]        # ':' means all rows(left)      and (right) side is for column
arr1[1:,1:3]     # column ek badha k likhna or row ko ek khata k...

array([4, 8, 6])

In [21]:
arr1[1:,3:5]

array([[7, 5],
       [5, 4]])

In [26]:
arr1[:,3:]

array([[6, 7],
       [7, 5],
       [5, 4]])

In [63]:
arr1[:,0]
arr1[:,-1]

array([7, 5, 4])